server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///E:/Microservice/config-repo
          default-label: main
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
